services:
  cfdnsclient:
    build:
      context: .
    restart: unless-stopped
    container_name: cfdnsclient
    networks:
      - main
    volumes:
      - ./config.json:/app/config.json

networks:
  main:
    enable_ipv6: true